//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs_Oil
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_CostCalculations
    {
        public int CCalculation_Id { get; set; }
        public int FK_User_Id { get; set; }
        public double Distance { get; set; }
        public double Consuption { get; set; }
        public int FK_Type_Id { get; set; }
        public double ResultsL { get; set; }
        public double ResultsC { get; set; }
    
        public virtual K_TypeFuel K_TypeFuel { get; set; }
        public virtual K_Users K_Users { get; set; }
    }
}
